name: CI Pipeline
# This Pipeline tests source code for:
# - Compilation (if it is compiling with no warnings or errors)
# - Unitary tests (if the library works as intended, compared to its STL counterpart).
# - Memory error detection (detecting memory errors such as memory leaks, invalid memory accesses, and uses of uninitialized memory)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compilation-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from Github
      uses: actions/checkout@v3
    - name: compilation check
      run: make build

  unit-tests-checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from Github
      uses: actions/checkout@v3
    - name: unit tests check
      run: make test_all

  valgrind-checks:
    runs-on: ubuntu-latest
    steps:
    - name: install valgrind
      run: sudo apt-get install valgrind
    - name: checkout from Github
      uses: actions/checkout@v3
    - name: memory error detection
      run: make test_all_vg
